import java.util.ArrayList;

public class MasterList
{
    static ArrayList<Song> masterPlaylist = new ArrayList<Song>();

    public static void fillPlaylist()
    {
        masterPlaylist.add(new Song("Bad Romance", "Lady Gaga", "pop", 4.55, false));
        masterPlaylist.add(new Song("Single Ladies (Put a Ring on It)","Beyoncé","pop", 3.13, false));
        masterPlaylist.add(new Song("Can't Get You Out of My Head", "Kylie Minogue", "pop", 3.50, false));
        masterPlaylist.add(new Song("Rockabye", "Clean Bandit(Feat. Sean Paul and Anne Marie)", "pop", 4.10, false));
        masterPlaylist.add(new Song("Take On Me", "a-ha", "pop", 3.45, false));
        masterPlaylist.add(new Song("Le Freak", "CHIC", "pop", 3.30, false));
        masterPlaylist.add(new Song("Hungry Like The Wolf", "Duran", "Duran", 3.40, false));
        masterPlaylist.add(new Song("New Rules", "Dua Lipa", "pop", 3.29, false));
        masterPlaylist.add(new Song("Crazy", "Gnarls Barkley", "pop", 2.57, false));
        masterPlaylist.add(new Song("Cake by the Ocean", "DNCE", "pop", 3.39, false));
        masterPlaylist.add(new Song("Weak", "AJR", "pop", 3.21, false));
        masterPlaylist.add(new Song("Roar", "Katy Perry", "pop", 3.43, false));
        masterPlaylist.add(new Song("Castle on the Hill", "Ed Sheeran", "pop", 4.21, false));
        masterPlaylist.add(new Song("Blinding Lights", "The Weeknd", "pop", 3.20, false));
        masterPlaylist.add(new Song("ME!", "Taylor Swift(Feat. Brendon Urie)", "pop", 3.13, false));
        masterPlaylist.add(new Song("Senorita", "Shawn Mendes and Camila Cabello", "pop", 3.10, false));
        masterPlaylist.add(new Song("bad guy", "Billie Eilish", "pop", 3.14, false));
        masterPlaylist.add(new Song("Memories", "Maroon 5", "pop", 3.09, false));
        masterPlaylist.add(new Song("Blank Space", "Taylor Swift", "pop", 3.15, false));
        masterPlaylist.add(new Song("Hollaback Girl", "Gwen Stefani", "pop", 3.19, false));
        masterPlaylist.add(new Song("A Sky Full of Star", "Coldplay", "pop", 4.27, false));
        masterPlaylist.add(new Song("Bad Liar", "Imagine Dragons", "pop", 4.20, false));
        masterPlaylist.add(new Song("Sk8ter Boy", "Avril Lavigne", "pop", 3.24, false));
        masterPlaylist.add(new Song("...Baby One More Time", "Britney Spears", "pop", 3.31, false));
        masterPlaylist.add(new Song("Cupids Chokehold / Breakfast in America", "Gym Class Heros", "pop", 4.03, false));
        masterPlaylist.add(new Song("Hips Don't Lie", "Shakira(Feat. Wyclef Jean)", "pop", 3.38, false));
        masterPlaylist.add(new Song("I Knew You Were Trouble.", "Taylor Swift", "pop", 3.39, false));
        masterPlaylist.add(new Song("Poker Face", "Lady Gaga", "pop", 4.02, false));
        masterPlaylist.add(new Song("Umbrella", "Rihanna and JAY-Z", "pop", 4.35, false));
        masterPlaylist.add(new Song("Moonlight", "Grace VanderWaal", "pop", 2.54, false));
        masterPlaylist.add(new Song("CAN'T STOP THE FEELING", "Justin Timberlake", "pop", 3.57, false));
        masterPlaylist.add(new Song("Sugar", "Maroon 5", "pop", 3.65, false));
        masterPlaylist.add(new Song("Havana", "Camila Cabello(Feat. Young Thug)", "pop", 3.37, false));
        masterPlaylist.add(new Song("Cool for the Summer", "Demi Levato", "pop", 3.34, false));
        masterPlaylist.add(new Song("Party In The U.S.A.", "Miley Cyrus", "pop", 3.22, false));
        masterPlaylist.add(new Song("Can't Hold Us", "Macklemore & Ryan Lewis(Feat. Ray Dalton)", "pop", 4.18, false));
        masterPlaylist.add(new Song("Burn", "Ellie Goulding", "pop", 3.51, false));
        masterPlaylist.add(new Song("Chandelier", "Sia", "pop", 3.36, false));
        masterPlaylist.add(new Song("Rude", "MAGIC!", "pop", 3.44, false));
        masterPlaylist.add(new Song("Sorry", "Justin Bieber", "pop", 3.20, false));
        masterPlaylist.add(new Song("Shape of You", "Ed Sheeran", "pop", 3.53, false));
        masterPlaylist.add(new Song("We Are Never Ever Getting Back Together", "Taylor Swift", "pop", 3.13, false));
        masterPlaylist.add(new Song("Just the Way You Are", "Bruno Mars", "pop", 3.40, false));
        masterPlaylist.add(new Song("Shake It Off", "Taylor Swift", "pop", 3.39, false));
        masterPlaylist.add(new Song("Sign of the Times", "Harry Styles", "pop", 5.40, false));
        masterPlaylist.add(new Song("Don't Let Me Down", "The Chainsmokers and Daya", "pop", 3.28, false));
        masterPlaylist.add(new Song("Royals", "Lorde", "pop", 3.10, false));
        masterPlaylist.add(new Song("Payphone", "Maroon 5 and Wiz Kalifa", "pop", 3.51, false));
        masterPlaylist.add(new Song("I Want It That Way", "Backstreet Boys", "pop", 3.33, false));
        masterPlaylist.add(new Song("Paradise", "Coldplay", "pop", 4.38, false));
        masterPlaylist.add(new Song("Hello", "Adele", "pop", 4.55, false));
        masterPlaylist.add(new Song("Say It Ain't So", "Weezer", "alternative", 4.18, false));
        masterPlaylist.add(new Song("Letter to Memphis", "Pixies", "alternative", 2.40, false));
        masterPlaylist.add(new Song("Zero", "The Smashing Pumpkins", "alternative", 2.40, false));
        masterPlaylist.add(new Song("Best Of You", "Foo Fighters", "alternative", 4.15, false));
        masterPlaylist.add(new Song("The Middle", "Jimmy Eat World", "alternative", 2.45, false));
        masterPlaylist.add(new Song("Plush", "Stone Temple Pilots", "alternative", 5.13, false));
        masterPlaylist.add(new Song("Sweater Weather", "The Neighborhood", "alternative", 4.00, false));
        masterPlaylist.add(new Song("Mr. Brightside", "The Killers", "alternative", 3.42, false));
        masterPlaylist.add(new Song("Feel Good Inc.", "Gorilliaz", "alternative", 3.42, false));
        masterPlaylist.add(new Song("Do I Wanna Know", "Arctic Monkeys", "alternative", 4.32, false));
        masterPlaylist.add(new Song("Creep", "Radiohead", "alternative", 3.58, false));
        masterPlaylist.add(new Song("Cigarette Daydreams", "Cage The Elephant", "alternative", 3.28, false));
        masterPlaylist.add(new Song("Float On", "Modest Mouse", "alternative", 3.28, false));
        masterPlaylist.add(new Song("Dog Days Are Over", "Florence + The Machine", "alternative", 4.11, false));
        masterPlaylist.add(new Song("Seven Nation Army", "The White Stripes", "alternative", 3.52, false));
        masterPlaylist.add(new Song("In The End", "Linkin Park", "alternative", 3.36, false));
        masterPlaylist.add(new Song("Stressed Out", "Twenty One Pilots", "alternative", 3.22, false));
        masterPlaylist.add(new Song("Viva La Vida", "Coldplay", "alternative", 4.02, false));
        masterPlaylist.add(new Song("Pumped Up Kicks", "Foster The People", "alternative", 3.59, false));
        masterPlaylist.add(new Song("Everlong", "Foo Fighter", "alternative", 4.10, false));
        masterPlaylist.add(new Song("Numb", "Linkin Park", "alternative", 3.05, false));
        masterPlaylist.add(new Song("All The Small Things", "blink-182", "alternative", 2.47, false));
        masterPlaylist.add(new Song("Zombie", "The Cranberries", "alternative", 5.06, false));
        masterPlaylist.add(new Song("Misery Business", "Paramore", "alternative", 3.31, false));
        masterPlaylist.add(new Song("Heathens", "Twenty One Pilots", "alternative", 3.15, false));
        masterPlaylist.add(new Song("Teenagers", "My Chemical Romance", "alternative", 2.41, false));
        masterPlaylist.add(new Song("Bring Me To Life", "Evanescence", "alternative", 3.55, false));
        masterPlaylist.add(new Song("Basket Case", "Green Day", "alternative", 3.01, false));
        masterPlaylist.add(new Song("The Reason", "Hoobastank", "alternative", 3.52, false));
        masterPlaylist.add(new Song("Centuries", "Fall Out Boy", "alternative", 3.48, false));
        masterPlaylist.add(new Song("Bitter Sweet Symphony", "The Verve", "alternative", 5.57, false));
        masterPlaylist.add(new Song("Otherside", "Red Hot Chilli Peppers", "alternative", 4.15, false));
        masterPlaylist.add(new Song("Chasing Cars", "Snow Patrol", "alternative", 4.27, false));
        masterPlaylist.add(new Song("Smells Like Teen Spirit", "Nirvana", "alternative", 5.01, false));
        masterPlaylist.add(new Song("Tongue Tied", "Grouplove", "alternative", 3.38, false));
        masterPlaylist.add(new Song("American Idiot", "Green Day", "alternative", 3.38, false));
        masterPlaylist.add(new Song("Take Me Out", "Fraz Ferdinand", "alternative", 3.57, false));
        masterPlaylist.add(new Song("The Pretender", "Foo Fighters", "alternative", 4.29, false));
        masterPlaylist.add(new Song("Island In The Sun", "Weezer", "alternative", 3.20, false));
        masterPlaylist.add(new Song("Welcome to the Black Parade", "My Chemical Romance", "alternative", 5.11, false));
        masterPlaylist.add(new Song("Kids", "MGMT", "alternative", 5.02, false));
        masterPlaylist.add(new Song("Sugar, We're Going Down", "Fall Out Boy", "alternative", 3.49, false));
        masterPlaylist.add(new Song("Somebody Told Me", "The Killers", "alternative", 3.42, false));
        masterPlaylist.add(new Song("Cough Syrup", "Young the Giant", "alternative", 4.09, false));
        masterPlaylist.add(new Song("A-Punk", "Vampire Weekend", "alternative", 2.17, false));
        masterPlaylist.add(new Song("Here To Forever", "Death Cab For Cutie", "alternative", 3.46, false));
        masterPlaylist.add(new Song("Sugar Soaker", "Panic! At Disco", "alternative", 3.11, false));
        masterPlaylist.add(new Song("Crazy = Genius", "Panic! At The Disco", "alternative", 3.18, false));
        masterPlaylist.add(new Song("Radioactive", "Imagine Dragons", "alternative", 3.06, false));
        masterPlaylist.add(new Song("Come As You Are", "Nirvana", "alternative", 3.38, false));
        masterPlaylist.add(new Song("Xatar", "23", "hip-hop", 2.04, false));
        masterPlaylist.add(new Song("More Life - Extended Version", "Yasin", "hip-hop", 2.27, false));
        masterPlaylist.add(new Song("Lotta & Sanna", "Mohela", "hip-hop", 2.15, false));
        masterPlaylist.add(new Song("All Eyez On Me", "2Pac(Feat. Big Syke)", "hip-hop", 5.07, false));
        masterPlaylist.add(new Song("Forget About Dre", "Dr.Dre and Eminem", "hip-hop", 3.42, false));
        masterPlaylist.add(new Song("Hate It Or Love It", "The Game and 50 Cent", "hip-hop", 3.26, false));
        masterPlaylist.add(new Song("Without Me", "Emminem", "hip-hop", 4.50, false));
        masterPlaylist.add(new Song("Tequila Sunrise", "Cypress Hill and Barron Ricks", "hip-hop", 4.17, false));
        masterPlaylist.add(new Song("Hail Mary", "Makaveli", "hip-hop", 5.09, false));
        masterPlaylist.add(new Song("My Band", "D12", "hip-hop", 4.58, false));
        masterPlaylist.add(new Song("Mass Appeal", "Gang Star", "hip-hop", 3.41, false));
        masterPlaylist.add(new Song("Gimme the Loot", "The Notorious B.I.G.", "hip-hop", 4.45, false));
        masterPlaylist.add(new Song("The Message", "Nas", "hip-hop", 3.54, false));
        masterPlaylist.add(new Song("You Know How We Do It", "Ice Cube", "hip-hop", 3.52, false));
        masterPlaylist.add(new Song("N.Y. State of Mind", "Nas", "hip-hop", 4.53, false));
        masterPlaylist.add(new Song("Work", "Gang Star", "hip-hop", 2.56, false));
        masterPlaylist.add(new Song("So Fresh, So Clean", "Outkast", "hip-hop", 4.00, false));
        masterPlaylist.add(new Song("Doja", "Central Cee", "hip-hop", 1.37, false));
        masterPlaylist.add(new Song("GO AGAIN - Intro", "DaBaby", "hip-hop", 2.06, false));
        masterPlaylist.add(new Song("N95", "Kendrick Lamar", "hip-hop", 1.39, false));
        masterPlaylist.add(new Song("Dior", "Pop Smoke", "hip-hop", 3.36, false));
        masterPlaylist.add(new Song("Motley Crew", "Post Malone", "hip-hop", 3.04, false));
        masterPlaylist.add(new Song("WHATS POPPIN", "Jack Harlow(Feat. DaBaby, Tony Lanez, and Lil Wayne)", "hip-hop", 3.47, false));
        masterPlaylist.add(new Song("2 Mins of Pain", "Sleepy Hallow", "hip-hop", 2.16, false));
        masterPlaylist.add(new Song("Ball If I Want To", "DaBaby", "hip-hop", 1.52, false));
        masterPlaylist.add(new Song("Up", "Cardi B", "hip-hop", 2.36, false));
        masterPlaylist.add(new Song("Hall Of Fame", "Young Dolph", "hip-hop", 3.58, false));
        masterPlaylist.add(new Song("Ambition For Cash", "Key Glock", "hip-hop", 2.23, false));
        masterPlaylist.add(new Song("Hot", "Young Thug(Feat. Gunna)", "hip-hop", 3.13, false));
        masterPlaylist.add(new Song("Lift Me Up", "Tyga", "hip-hop", 2.48, false));
        masterPlaylist.add(new Song("AP", "Pop Smoke", "hip-hop", 2.51, false));
        masterPlaylist.add(new Song("I Get the Bag", "Gucci Mane(Feat. Migos)", "hip-hop",3.54, false));
        masterPlaylist.add(new Song("Talk", "Yeat", "hip-hop", 2.45, false));
        masterPlaylist.add(new Song("Beat the Odds", "Lil Tjay", "hip-hop", 2.30, false));
        masterPlaylist.add(new Song("SOCKS", "DaBaby", "hip-hop", 2.51, false));
        masterPlaylist.add(new Song("True Love", "Kanye West and XXXTENTACION", "hip-hop", 2.28, false));
        masterPlaylist.add(new Song("Churchill Downs", "Jack Harlow(Feat. Drake)", "hip-hop", 5.09, false));
        masterPlaylist.add(new Song("EVERY CHANCE I GET", "DJ Kalid(Feat. Lil Baby and Lil Durk", "hip-hop", 3.56, false));
        masterPlaylist.add(new Song("What's Next", "Drake", "hip-hop", 2.58, false));
        masterPlaylist.add(new Song("GTG", "Freddie Dredd", "hip-hop", 1.33, false));
        masterPlaylist.add(new Song("Sometimes", "Juice WRLD", "hip-hop", 4.19, false));
        masterPlaylist.add(new Song("Faster", "Lil Tecca", "hip-hop", 2.09, false));
        masterPlaylist.add(new Song("Back In Blood", "Pooh Shiesty(Feat. Lil Durk)", "hip-hop", 3.04, false));
        masterPlaylist.add(new Song("Dance Now", "JID(Feat/ Kenny Mason)", "hip-hop", 3.47, false));
        masterPlaylist.add(new Song("54321", "Offset", "hip-hop", 3.02, false));
        masterPlaylist.add(new Song("Umm Hmm", "Young Boy Never Broke Again", "hip-hop", 2.12, false));
        masterPlaylist.add(new Song("Faster", "Lil Tecca", "hip-hop", 2.09, false));
        masterPlaylist.add(new Song("Fantastic", "Tyga", "hip-hop", 2.52, false));
        masterPlaylist.add(new Song("Goin Up", "Lil Tjay", "hip-hop", 2.59, false));
        masterPlaylist.add(new Song("Black Hearted", "Polo G", "hip-hop", 3.10, false));
        masterPlaylist.add(new Song("No Surprises", "Radiohead", "rock", 3.49, false));
        masterPlaylist.add(new Song("Beth", "KISS", "rock", 2.45, false));
        masterPlaylist.add(new Song("Iris", "The Goo Goo Dolls", "rock", 4.49, false));
        masterPlaylist.add(new Song("Rock You Like A Hurricane", "Scorpions", "rock", 4.12, false));
        masterPlaylist.add(new Song("Cryin'", "Aerosmith", "rock", 5.08, false));
        masterPlaylist.add(new Song("Barracuda", "Heart", "rock", 4.21, false));
        masterPlaylist.add(new Song("Be Yourself", "Audioslave", "rock", 4.38, false));
        masterPlaylist.add(new Song("I Was Made For Lovin' You", "Kiss", "rock", 4.31, false));
        masterPlaylist.add(new Song("Killing In The Name", "Rage Against The Machine", "rock", 5.13, false));
        masterPlaylist.add(new Song("Roxane", "The Police", "rock", 3.11, false));
        masterPlaylist.add(new Song("Nothing Else Matters", "Metallic", "rock", 6.28, false));
        masterPlaylist.add(new Song("Smoke on the Water", "Deep Purple", "rock", 5.42, false));
        masterPlaylist.add(new Song("Thunderstruck", "AC/DC", "rock", 4.52, false));
        masterPlaylist.add(new Song("I Wanna Rock", "Twisted Sister", "rock", 2.59, false));
        masterPlaylist.add(new Song("Rock You Like A Hurricane", "Scorpians", "rock", 4.12, false));
        masterPlaylist.add(new Song("Whole Lotta Love", "Led Zeppelin", "rock", 5.33, false));
        masterPlaylist.add(new Song("Sweet Child O' Mine", "Guns N' Roses", "rock", 5.56, false));
        masterPlaylist.add(new Song("Master of Puppets", "Metallica", "rock", 8.35, false));
        masterPlaylist.add(new Song("Crazy Train", "Ozzy Ozbourne", "rock", 4.53, false));
        masterPlaylist.add(new Song("Back In Black", "AC/DC", "rock", 4.15, false));
        masterPlaylist.add(new Song("Heaven's On Fire", "KISS", "rock", 3.21, false));
        masterPlaylist.add(new Song("Jump", "Van Halen", "rock", 4.01, false));
        masterPlaylist.add(new Song("18 and Life", "Skid Row", "rock", 3.49, false));
        masterPlaylist.add(new Song("In the End", "Linkin Park", "rock", 3.36, false));
        masterPlaylist.add(new Song("The Kids Aren't Alright", "The Offspring", "rock", 3.00, false));
        masterPlaylist.add(new Song("All My Life", "Foo Fighters", "rock", 4.23, false));
        masterPlaylist.add(new Song("Highway to Hell", "AC/DC", "rock", 3.28, false));
        masterPlaylist.add(new Song("Knockin' On Heaven's Door", "Guns N' Roses", "rock", 5.36, false));
        masterPlaylist.add(new Song("Poison", "Alice Cooper", "rock", 4.30, false));
        masterPlaylist.add(new Song("About A Girl", "Nirvana", "rock", 2.46, false));
        masterPlaylist.add(new Song("Higher", "Creed", "rock", 5.16, false));
        masterPlaylist.add(new Song("Amazing", "Aerosmith", "rock", 5.56, false));
        masterPlaylist.add(new Song("My Generation", "The Who", "rock", 3.18, false));
        masterPlaylist.add(new Song("Can't Stop Lovin' You", "Van Halen", "rock", 4.07, false));
        masterPlaylist.add(new Song("boy", "The Killers", "rock", 3.18, false));
        masterPlaylist.add(new Song("SUPERMODEL", "Maneskin", "rock", 2.28, false));
        masterPlaylist.add(new Song("Wild Child", "The Black Keys", "rock", 2.44, false));
        masterPlaylist.add(new Song("Something Loud", "Jimmy Eat World", "rock", 3.16, false));
        masterPlaylist.add(new Song("Mary On A Cross", "Ghost", "rock", 4.04, false));
        masterPlaylist.add(new Song("The Foundations Of Decay", "My Chemical Romance", "rock", 6.00, false));
        masterPlaylist.add(new Song("sTraNgeRs", "Bring Me The Horizon", "rock", 3.15, false));
        masterPlaylist.add(new Song("FUNERAL GREY", "Waterparks", "rock", 2.44, false));
        masterPlaylist.add(new Song("Broken", "Payle Royale", "rock", 3.10, false));
        masterPlaylist.add(new Song("Miracle", "A Day to Remember", "rock", 4.03, false));
        masterPlaylist.add(new Song("Times Like These", "Five Finger Death Punch", "rock", 3.29, false));
        masterPlaylist.add(new Song("Hey You", "Disturbed", "rock", 4.28, false));
        masterPlaylist.add(new Song("Yen", "Slipknot", "rock", 4.43, false));
        masterPlaylist.add(new Song("San Quentin", "Nickleback", "rock", 3.31, false));
        masterPlaylist.add(new Song("Rotoscope", "Spiritbox", "rock", 3.35, false));
        masterPlaylist.add(new Song("DEEP CUTS", "You Me At Six", "rock", 4.14, false));
        masterPlaylist.add(new Song("Fantasy", "RIOPY", "classical", 4.25, true));
        masterPlaylist.add(new Song("Sincère", "Matteo Myderwyk", "classical", 3.23, true));
        masterPlaylist.add(new Song("Franck: Prelude", "César Franck", "classical", 3.45, true));
        masterPlaylist.add(new Song("A Gentle Sunlight", "James Quinn", "classical", 1.57, true));
        masterPlaylist.add(new Song("senna's joy", "Carlos Cipa", "classical", 6.16, true));
        masterPlaylist.add(new Song("Salon musique", "Maxence Cyrin", "classical", 2.00, true));
        masterPlaylist.add(new Song("Un sourire et une larme", "Tom Kristiaan", "classical", 2.26, true));
        masterPlaylist.add(new Song("Beethoven: Bagastelle No. 25", "Ludwig van Beetoven", "classical", 2.26, true));
        masterPlaylist.add(new Song("Petite ouverture à danser", "Erik Satie", "classical", 5.19, true));
        masterPlaylist.add(new Song("In Due Time", "Jasoer Harris", "classical", 1.41, true));
        masterPlaylist.add(new Song("The First Waltz", "RIOPY", "classical", 2.46, true));
        masterPlaylist.add(new Song("Debussy: Arabesque No. 1", "Calusw Debussy", "classical", 3.30, true));
        masterPlaylist.add(new Song("Flowwwwwwwww", "Adrian Kuipers", "classical", 3.22, true));
        masterPlaylist.add(new Song("L'Automne du Coeur", "Coen Molenaar", "classical", 3.24, true));
        masterPlaylist.add(new Song("Lauren", "James Homard", "classical", 2.00, true));
        masterPlaylist.add(new Song("Water Lilies", "John Vegard Schow", "classical", 2.00, true));
        masterPlaylist.add(new Song("Venetian Gondola", "Oscar Pascasio", "classical", 2.35, true));
        masterPlaylist.add(new Song("Eclipse", "Raffaele Grimaldi", "classical", 3.10, true));
        masterPlaylist.add(new Song("Eyes Closed", "Melinda Sütö", "classical", 3.15, true));
        masterPlaylist.add(new Song("Light between the lines", "Christian Janssen", "classical", 1.52, true));
        masterPlaylist.add(new Song("Deliverence", "Pieter Savenburg", "classical", 2.21, true));
        masterPlaylist.add(new Song("comme l'oiseau", "Amelie Moulin", "classical", 2.16, true));
        masterPlaylist.add(new Song("Lament", "Lisa Kriegler", "classical", 2.20, true));
        masterPlaylist.add(new Song("Prefigure", "Yonder", "classical", 3.58, true));
        masterPlaylist.add(new Song("Red Door", "Kalas", "classical", 2.16, true));
        masterPlaylist.add(new Song("17th December 2020", "Fred Again..", "classical", 3.40, true));
        masterPlaylist.add(new Song("Journey", "Ron Adelaar", "classical", 2.22, true));
        masterPlaylist.add(new Song("Carvoeio", "Tjeerd Oosterhuis", "classical", 2.31, true));
        masterPlaylist.add(new Song("On The Way Home", "Dario Crisman", "classical", 2.26, true));
        masterPlaylist.add(new Song("You belong", "San fiore", "classical", 2.27, true));
        masterPlaylist.add(new Song("Gnossienne of a secret history", "Luna Acantha", "classical", 2.33, true));
        masterPlaylist.add(new Song("Blossom", "Dennis Korn", "classical", 1.31, true));
        masterPlaylist.add(new Song("Place dans ton coeur", "Marten LeGrand", "classical", 2.20, true));
        masterPlaylist.add(new Song("Sonder", "15.", "classical", 4.36, true));
        masterPlaylist.add(new Song("ascend", "Jacco Wynia", "classical", 2.13, true));
        masterPlaylist.add(new Song("Back to my roots", "Cristian Janssen", "classical", 2.34, true));
        masterPlaylist.add(new Song("Silent Alleys", "Luis Berra", "classical", 2.36, true));
        masterPlaylist.add(new Song("Fauré", "Gabriel Fauré", "classical", 2.20, true));
        masterPlaylist.add(new Song("Waltz in E Minor", "Javi Lobe", "classical", 2.16, true));
        masterPlaylist.add(new Song("Alina", "Daniel Paterok", "classical", 2.10, true));
        masterPlaylist.add(new Song("Event Horizon", "Kalas", "classical", 2.15, true));
        masterPlaylist.add(new Song("Merel", "Yonder", "classical", 2.58, true));
        masterPlaylist.add(new Song("Sempre", "Lisa Kriegler", "classical", 2.41, true));
        masterPlaylist.add(new Song("Light Rays", "Counting Waves", "classical", 2.31, true));
        masterPlaylist.add(new Song("A Mile Away", "Cristian Vivaldi", "classical", 1.52, true));
        masterPlaylist.add(new Song("Elisa II", "heik", "classical", 2.58, true));
        masterPlaylist.add(new Song("Eventide", "Louis Mercier", "classical", 2.11, true));
        masterPlaylist.add(new Song("Bach, JS", "Johann Sebastian Bach", "classical", 3.25, true));
        masterPlaylist.add(new Song("La Cura de Lombao", "Bart Sunshine", "classical", 1.59, true));
        masterPlaylist.add(new Song("Cold Little Heart", "Aleksander Debicz", "classical", 3.36, true));
        masterPlaylist.add(new Song("Day Dream", "Bill Charlap Trio", "jazz", 6.13, true));
        masterPlaylist.add(new Song("Sometime Ago", "Madeleine West", "jazz", 2.40, true));
        masterPlaylist.add(new Song("Without A Song", "Meadow Park", "jazz", 3.56, true));
        masterPlaylist.add(new Song("Prelude To A Kiss", "Al Flower Trio", "jazz", 4.35, true));
        masterPlaylist.add(new Song("Autumn In New York", "Mayfare Trio", "jazz", 4.19, true));
        masterPlaylist.add(new Song("The Beauty of Everyday Things", "Hara Noda", "jazz", 3.23, true));
        masterPlaylist.add(new Song("What A Little Moonlight Can Do", "Gottfield Barber Trio", "jazz", 2.33, true));
        masterPlaylist.add(new Song("Love Will Last Forever", " Michael Stulez & Co", "jazz", 3.35, true));
        masterPlaylist.add(new Song("Pensativa", "Gene Hart Trio", "jazz", 4.47, true));
        masterPlaylist.add(new Song("Like Jazz or Something", "6th Street Jazz", "jazz", 3.25, true));
        masterPlaylist.add(new Song("Crystal Blue", "Jean-Baptiste Rees", "jazz", 2.48, true));
        masterPlaylist.add(new Song("Evening Silence", "Three Four Trio", "jazz", 4.27, true));
        masterPlaylist.add(new Song("All My Love", "The Collective", "jazz", 3.58, true));
        masterPlaylist.add(new Song("The Wind", "Wildflower Trio", "jazz", 3.57, true));
        masterPlaylist.add(new Song("Early Morning Thoughts", "Trio Del Norte", "jazz", 6.44, true));
        masterPlaylist.add(new Song("Miles and Miles", "Pimm's Trio", "jazz", 4.31, true));
        masterPlaylist.add(new Song("As Time Goes By", "The Headliner Trio", "jazz", 4.10, true));
        masterPlaylist.add(new Song("Bewitched", "Jaden Berry", "jazz", 3.27, true));
        masterPlaylist.add(new Song("Bring Some Lovin'", "Flatland Park", "jazz", 3.09, true));
        masterPlaylist.add(new Song("W 52nd Street", "Carlton Maison Quartet", "jazz", 3.43, true));
        masterPlaylist.add(new Song("Constantly Changing", "Courtney Salas Group", "jazz", 3.17, true));
        masterPlaylist.add(new Song("Witness of Love", "Neil Champman Green", "jazz", 3.17, true));
        masterPlaylist.add(new Song("A Knock On the Door", "Clover Post", "jazz", 3.27, true));
        masterPlaylist.add(new Song("A Few Odd Jobs", "Tore Lundblad", "jazz", 3.12, true));
        masterPlaylist.add(new Song("Tell Me", "Foster Davis", "jazz", 4.24, true));
        masterPlaylist.add(new Song("Life In The Deepest Blue", "Astoria Three", "jazz", 2.53, true));
        masterPlaylist.add(new Song("Clear Sight", "Midtown Trio", "jazz", 2.47, true));
        masterPlaylist.add(new Song("Solitude", "The Uptown Players", "jazz", 2.30, true));
        masterPlaylist.add(new Song("You're My Everything", "John B. Stewart", "jazz", 3.39, true));
        masterPlaylist.add(new Song("A Sleepin' Bee", "Bill Walton", "jazz", 3.42, true));
        masterPlaylist.add(new Song("Maze Of Tranquility", "Martin Landstrom", "jazz", 4.22, true));
        masterPlaylist.add(new Song("Déjà vu", "Eddie Harper", "jazz", 3.48, true));
        masterPlaylist.add(new Song("Mancuso's Joint", "Norris Walker Trio", "jazz", 4.18, true));
        masterPlaylist.add(new Song("It's Always You", "Bill Parker", "jazz", 3.39, true));
        masterPlaylist.add(new Song("More Than You Know", "Charlie Regan Three", "jazz", 4.21, true));
        masterPlaylist.add(new Song("Northwood Hills", "Long Island Quartet", "jazz", 3.14, true));
        masterPlaylist.add(new Song("Easy To Love", "Mike Coen", "jazz", 3.23, true));
        masterPlaylist.add(new Song("Stars Fell On Alabama", "Mark Roswell Trio", "jazz", 4.04, true));
        masterPlaylist.add(new Song("Blue Room", "Astoria Three", "jazz", 2.38, true));
        masterPlaylist.add(new Song("Nancy (With the Laughing Face", "Cecil Andrews", "jazz", 4.05, true));
        masterPlaylist.add(new Song("Don't Go To Strangers", "Old Town Trio", "jazz", 4.02, true));
        masterPlaylist.add(new Song("You're Just Full of Inspiration", "Lachan Wright Trio", "jazz", 2.24, true));
        masterPlaylist.add(new Song("Midday Walk", "Lodt Trio", "jazz", 3.31, true));
        masterPlaylist.add(new Song("I Got It Bad", "Eric Rowland", "jazz", 4.26, true));
        masterPlaylist.add(new Song("It's You Or No One", "The Blue Green", "jazz", 3.34, true));
        masterPlaylist.add(new Song("I Still See You In My Dreams", "Japari Park", "jazz", 3.17, true));
        masterPlaylist.add(new Song("Waiting", "Streetlight Trio", "jazz", 3.21, true));
        masterPlaylist.add(new Song("These Foolish Things", "Tribute Trio", "jazz", 4.50, true));
        masterPlaylist.add(new Song("Down the Pawn Shop", "Louie Hobbs Trio", "jazz", 3.26, true));
        masterPlaylist.add(new Song("Polkadots and Moonbeams", "Reuben Plays", "jazz", 3.42, true));
        masterPlaylist.add(new Song("When You Die", "MGMT", "indie", 4.23, false));
        masterPlaylist.add(new Song("Little Talks", "Of Monsters and Men", "indie", 4.26, false));
        masterPlaylist.add(new Song("West Coast", "The Neighborhood", "indie", 4.13, false));
        masterPlaylist.add(new Song("My Number", "Foals", "indie", 3.58, false));
        masterPlaylist.add(new Song("A-Punk", "Vampire Weekend", "indie", 2.17, false));
        masterPlaylist.add(new Song("Don't Look Back into the Sun", "The Libertines", "indie", 3.00, false));
        masterPlaylist.add(new Song("When The Sun Goes Down", "Arctic Monkeys", "indie", 3.22, false));
        masterPlaylist.add(new Song("What You Know", "Two Door Cinema Club", "indie", 3.11, false));
        masterPlaylist.add(new Song("Hang Me Up To Dry", "Cold War Kids", "indie", 3.38, false));
        masterPlaylist.add(new Song("Under Cover of Darkness", "The Strokes", "indie", 3.55, false));
        masterPlaylist.add(new Song("Always Where I Need To Be", "The Kooks", "indie", 2.41, false));
        masterPlaylist.add(new Song("Fire", "Kasabian", "indie", 4.12, false));
        masterPlaylist.add(new Song("Men's Needs", "The Cribs", "indie", 3.15, false));
        masterPlaylist.add(new Song("Sheila", "Jamie T", "indie", 4.19, false));
        masterPlaylist.add(new Song("Obstacle 1", "Interpol", "indie", 4.11, false));
        masterPlaylist.add(new Song("I Bet You Look Good", "Arctic Monkeys", "indie", 2.53, false));
        masterPlaylist.add(new Song("Naive", "The Kooks", "indie", 3.23, false));
        masterPlaylist.add(new Song("Banquet", "Bloc Party", "indie", 3.16, false));
        masterPlaylist.add(new Song("Young Folks", "Peter Bjorn and John", "indie", 4.36, false));
        masterPlaylist.add(new Song("Twice", "Catfish and the Bottlemen", "indie", 3.16, false));
        masterPlaylist.add(new Song("Australia", "The Shins", "indie", 3.56, false));
        masterPlaylist.add(new Song("Mardy Bum", "Arctic Monkeys", "indie", 2.55, false));
        masterPlaylist.add(new Song("Take Me Out", "Franz Ferdinand", "indie", 3.57, false));
        masterPlaylist.add(new Song("Helicopter", "Bloc Party", "indie", 3.40, false));
        masterPlaylist.add(new Song("Shuffle", "Bombay Bicycle Club", "indie", 3.55, false));
        masterPlaylist.add(new Song("Rebellian (Lies)", "Arcade Fire", "indie", 5.10, false));
        masterPlaylist.add(new Song("Way It Goes", "Hippo Campus", "indie", 4.05, false));
        masterPlaylist.add(new Song("Junk Of The Heart(Happy)", "The Kooks", "indie", 3.07, false));
        masterPlaylist.add(new Song("In The Morning", "Razorlight", "indie", 3.41, false));
        masterPlaylist.add(new Song("T-Shirt Weather", "Circa Waves", "indie", 3.12, false));
        masterPlaylist.add(new Song("Mountain at My Gates", "Foals", "indie", 4.04, false));
        masterPlaylist.add(new Song("Zombie", "Jamie T", "indie", 4.06, false));
        masterPlaylist.add(new Song("Farewell To The Fairground", "White Lies", "indie", 4.16, false));
        masterPlaylist.add(new Song("Someday", "The Strokes", "indie", 3.03, false));
        masterPlaylist.add(new Song("The Great Escape", "We Are Scientists", "indie", 3.18, false));
        masterPlaylist.add(new Song("Always Like This", "Bombay Bicycle Club", "indie", 4.05, false));
        masterPlaylist.add(new Song("The Funeral", "Band of Horses", "indie", 5.22, false));
        masterPlaylist.add(new Song("Money", "The Drums", "indie", 3.53, false));
        masterPlaylist.add(new Song("Last Nite", "The Strokes", "indie", 3.13, false));
        masterPlaylist.add(new Song("Underdog", "Kasabian", "indie", 4.37, false));
        masterPlaylist.add(new Song("Apply Some Pressure", "Maximo Park", "indie", 3.20, false));
        masterPlaylist.add(new Song("Evil", "Interpol", "indie", 3.35, false));
        masterPlaylist.add(new Song("1901", "Phoenix", "indie", 3.13, false));
        masterPlaylist.add(new Song("Sleepyhead", "Passion Pit", "indie", 2.54, false));
        masterPlaylist.add(new Song("A Certain Romance", "Arctic Monkeys", "indie", 5.31, false));
        masterPlaylist.add(new Song("Red Eyes", "The War On Drugs", "indie", 4.58, false));
        masterPlaylist.add(new Song("When Am I Gonna Lose You", "Local Natives", "indie", 4.24, false));
        masterPlaylist.add(new Song("Cocoon", "Catfish and the Bottlemen", "indie", 3.56, false));
        masterPlaylist.add(new Song("We'll Live And Die", "The Enemy", "indie", 3.52, false));
        masterPlaylist.add(new Song("Can't Stand Me Know", "The Libertines", "indie", 3.23, false));
        masterPlaylist.add(new Song("Should I Stay or Should I Go", "The Clash", "punk rock", 3.08, false));
        masterPlaylist.add(new Song("Human Fly", "The Cramps", "punk rock", 2.16, false));
        masterPlaylist.add(new Song("Holiday in Cambodia", "Dead Kennedys", "punk rock", 3.44, false));
        masterPlaylist.add(new Song("I Fought the Law", "The Clash", "punk rock", 3.44, false));
        masterPlaylist.add(new Song("Blister In The Sun", "Violent Femmes", "punk rock", 2.25, false));
        masterPlaylist.add(new Song("Where Eagles Dare", "Misfits", "punk rock", 2.08, false));
        masterPlaylist.add(new Song("I Wanna Be Sedated", "Ramones", "punk rock", 2.29, false));
        masterPlaylist.add(new Song("Lust For Life", "Iggy Pop", "punk rock", 5.12, false));
        masterPlaylist.add(new Song("One Way Or Another", "Blondie", "punk rock", 3.37, false));
        masterPlaylist.add(new Song("Blitzkrieg Bop", "Ramones", "punk rock", 2.14, false));
        masterPlaylist.add(new Song("Cherry Bomb", "The Runaways", "punk rock", 2.18, false));
        masterPlaylist.add(new Song("Alternative Ulster", "Stiff Little Fingers", "punk rock", 2.43, false));
        masterPlaylist.add(new Song("London Calling", "The Clash", "punk rock", 3.20, false));
        masterPlaylist.add(new Song("Disorder", "Joy Division", "punk rock", 3.29, false));
        masterPlaylist.add(new Song("Monor Threat", "Minor Threat", "punk rock", 1.29, false));
        masterPlaylist.add(new Song("Waiting Room", "Fugazi", "punk rock", 2.53, false));
        masterPlaylist.add(new Song("Rock 'n' Roll High School", "Ramones", "punk rock", 2.17, false));
        masterPlaylist.add(new Song("Marquee Moon", "Television", "punk rock", 10.38, false));
        masterPlaylist.add(new Song("Hope", "Descendents", "punk rock", 2.00, false));
        masterPlaylist.add(new Song("Pump It Up", "Elvis Costello & The Atrractions", "punk rock", 3.16, false));
        masterPlaylist.add(new Song("Rock the Casbah", "The Clash", "punk rock", 3.42, false));
        masterPlaylist.add(new Song("Let's Get Rid of NY", "The Randoms", "punk rock", 2.45, false));
        masterPlaylist.add(new Song("Rebel Rebel", "Davis Bowie", "punk rock", 4.34, false));
        masterPlaylist.add(new Song("(The Original) Neutron Bomb", "The Controllers", "punk rock", 2.05, false));
        masterPlaylist.add(new Song("Last Caress", "Misfits", "punk rock", 1.59, false));
        masterPlaylist.add(new Song("Judy Is a Punk", "Ramones", "punk rock", 1.32, false));
        masterPlaylist.add(new Song("Teenage Letter", "The Count Bishops", "punk rock", 2.25, false));
        masterPlaylist.add(new Song("Ever Fallen in Love (With Someone You Shoudn't've?)", "Buzzcocks", "punk rock", 2.43, false));
        masterPlaylist.add(new Song("(I'm) Stranded", "The Saints", "punk rock", 3.30, false));
        masterPlaylist.add(new Song("Police On My Back", "The Clash", "punk rock", 3.16, false));
        masterPlaylist.add(new Song("Once in a Lifetime", "Talking Heads", "punk rock", 4.19, false));
        masterPlaylist.add(new Song("California Uber Alles", "Dead Kennedys", "punk rock", 3.27, false));
        masterPlaylist.add(new Song("Damaged Goods", "Gang of Four", "punk rock", 3.26, false));
        masterPlaylist.add(new Song("Six Pack", "Black Flag", "punk rock", 3.26, false));
        masterPlaylist.add(new Song("No Control", "Bad Religon", "punk rock", 1.46, false));
        masterPlaylist.add(new Song("Institutionalized", "Suicidal Tendencies", "punk rock", 3.49, false));
        masterPlaylist.add(new Song("I Want Some", "Beastie Boys", "punk rock", 2.00, false));
        masterPlaylist.add(new Song("New Rose", "The Damned", "punk rock", 2.42, false));
        masterPlaylist.add(new Song("Rise Above", "Black Flag", "punk rock", 2.26, false));
        masterPlaylist.add(new Song("(You're A) Go Nowhere", "Reagan Youth", "punk rock", 1.22, false));
        masterPlaylist.add(new Song("Bastards of Young", "The Replacements", "punk rock", 3.38, false));
        masterPlaylist.add(new Song("Live Fast Die Young", "Circle Jerks", "punk rock", 1.33, false));
        masterPlaylist.add(new Song("Viet Nam", "Minutemen", "punk rock", 1.29, false));
        masterPlaylist.add(new Song("1969", "The Stooges", "punk rock", 4.05, false));
        masterPlaylist.add(new Song("Dig That Groove Baby", "Toy Dolls", "punk rock", 2.31, false));
        masterPlaylist.add(new Song("Maxwell Murder", "Rancid", "punk rock", 1.25, false));
        masterPlaylist.add(new Song("Suburban Home", "Descendents", "punk rock", 1.42, false));
        masterPlaylist.add(new Song("Sonic Reducer", "Dead Boys", "punk rock", 3.09, false));
        masterPlaylist.add(new Song("Euro-Barge", "The Vandals", "punk rock", 1.53, false));
        masterPlaylist.add(new Song("Main Offender", "The Hives", "punk rock", 2.33, false));
        masterPlaylist.add(new Song("Never Gonna Give You Up", "Rick Astley", "mongolian throat singing", 3.33, false));
        masterPlaylist.add(new Song("Never Gonna Give You Up", "Rick Astley", "mongolian throat singing", 3.33, false));
        masterPlaylist.add(new Song("Never Gonna Give You Up", "Rick Astley", "mongolian throat singing", 3.33, false));
        masterPlaylist.add(new Song("Never Gonna Give You Up", "Rick Astley", "mongolian throat singing", 3.33, false));
        masterPlaylist.add(new Song("Never Gonna Give You Up", "Rick Astley", "mongolian throat singing", 3.33, false));
        masterPlaylist.add(new Song("Never Gonna Give You Up", "Rick Astley", "mongolian throat singing", 3.33, false));
        masterPlaylist.add(new Song("Never Gonna Give You Up", "Rick Astley", "mongolian throat singing", 3.33, false));
        masterPlaylist.add(new Song("Never Gonna Give You Up", "Rick Astley", "mongolian throat singing", 3.33, false));
        masterPlaylist.add(new Song("Never Gonna Give You Up", "Rick Astley", "mongolian throat singing", 3.33, false));
        masterPlaylist.add(new Song("Never Gonna Give You Up", "Rick Astley", "mongolian throat singing", 3.33, false));
        masterPlaylist.add(new Song("Never Gonna Give You Up", "Rick Astley", "mongolian throat singing", 3.33, false));
        masterPlaylist.add(new Song("Never Gonna Give You Up", "Rick Astley", "mongolian throat singing", 3.33, false));
        masterPlaylist.add(new Song("Never Gonna Give You Up", "Rick Astley", "mongolian throat singing", 3.33, false));
        masterPlaylist.add(new Song("Never Gonna Give You Up", "Rick Astley", "mongolian throat singing", 3.33, false));
        masterPlaylist.add(new Song("Never Gonna Give You Up", "Rick Astley", "mongolian throat singing", 3.33, false));
        masterPlaylist.add(new Song("Never Gonna Give You Up", "Rick Astley", "mongolian throat singing", 3.33, false));
        masterPlaylist.add(new Song("Never Gonna Give You Up", "Rick Astley", "mongolian throat singing", 3.33, false));
        masterPlaylist.add(new Song("Never Gonna Give You Up", "Rick Astley", "mongolian throat singing", 3.33, false));
        masterPlaylist.add(new Song("Never Gonna Give You Up", "Rick Astley", "mongolian throat singing", 3.33, false));
        masterPlaylist.add(new Song("Never Gonna Give You Up", "Rick Astley", "mongolian throat singing", 3.33, false));
        masterPlaylist.add(new Song("Never Gonna Give You Up", "Rick Astley", "mongolian throat singing", 3.33, false));
        masterPlaylist.add(new Song("Never Gonna Give You Up", "Rick Astley", "mongolian throat singing", 3.33, false));
        masterPlaylist.add(new Song("Never Gonna Give You Up", "Rick Astley", "mongolian throat singing", 3.33, false));
        masterPlaylist.add(new Song("Never Gonna Give You Up", "Rick Astley", "mongolian throat singing", 3.33, false));
        masterPlaylist.add(new Song("Never Gonna Give You Up", "Rick Astley", "mongolian throat singing", 3.33, false));
        masterPlaylist.add(new Song("Never Gonna Give You Up", "Rick Astley", "mongolian throat singing", 3.33, false));
        masterPlaylist.add(new Song("Never Gonna Give You Up", "Rick Astley", "mongolian throat singing", 3.33, false));
        masterPlaylist.add(new Song("Never Gonna Give You Up", "Rick Astley", "mongolian throat singing", 3.33, false));
        masterPlaylist.add(new Song("Never Gonna Give You Up", "Rick Astley", "mongolian throat singing", 3.33, false));
        masterPlaylist.add(new Song("Never Gonna Give You Up", "Rick Astley", "mongolian throat singing", 3.33, false));
        masterPlaylist.add(new Song("Never Gonna Give You Up", "Rick Astley", "mongolian throat singing", 3.33, false));
        masterPlaylist.add(new Song("Never Gonna Give You Up", "Rick Astley", "mongolian throat singing", 3.33, false));
        masterPlaylist.add(new Song("Never Gonna Give You Up", "Rick Astley", "mongolian throat singing", 3.33, false));
        masterPlaylist.add(new Song("Never Gonna Give You Up", "Rick Astley", "mongolian throat singing", 3.33, false));
        masterPlaylist.add(new Song("Never Gonna Give You Up", "Rick Astley", "mongolian throat singing", 3.33, false));
        masterPlaylist.add(new Song("Never Gonna Give You Up", "Rick Astley", "mongolian throat singing", 3.33, false));
        masterPlaylist.add(new Song("Never Gonna Give You Up", "Rick Astley", "mongolian throat singing", 3.33, false));
        masterPlaylist.add(new Song("Never Gonna Give You Up", "Rick Astley", "mongolian throat singing", 3.33, false));
        masterPlaylist.add(new Song("Never Gonna Give You Up", "Rick Astley", "mongolian throat singing", 3.33, false));
        masterPlaylist.add(new Song("Never Gonna Give You Up", "Rick Astley", "mongolian throat singing", 3.33, false));
        masterPlaylist.add(new Song("Never Gonna Give You Up", "Rick Astley", "mongolian throat singing", 3.33, false));
        masterPlaylist.add(new Song("Never Gonna Give You Up", "Rick Astley", "mongolian throat singing", 3.33, false));
        masterPlaylist.add(new Song("Never Gonna Give You Up", "Rick Astley", "mongolian throat singing", 3.33, false));
        masterPlaylist.add(new Song("Never Gonna Give You Up", "Rick Astley", "mongolian throat singing", 3.33, false));
        masterPlaylist.add(new Song("Never Gonna Give You Up", "Rick Astley", "mongolian throat singing", 3.33, false));
        masterPlaylist.add(new Song("Never Gonna Give You Up", "Rick Astley", "mongolian throat singing", 3.33, false));
        masterPlaylist.add(new Song("Never Gonna Give You Up", "Rick Astley", "mongolian throat singing", 3.33, false));
        masterPlaylist.add(new Song("Never Gonna Give You Up", "Rick Astley", "mongolian throat singing", 3.33, false));
        masterPlaylist.add(new Song("Never Gonna Give You Up", "Rick Astley", "mongolian throat singing", 3.33, false));
        masterPlaylist.add(new Song("Never Gonna Give You Up", "Rick Astley", "mongolian throat singing", 3.33, false));
        masterPlaylist.add(new Song("misty nights", "steezy prime", "lo-fi", 2.35, true));
        masterPlaylist.add(new Song("Someone I've Lost", "Hoogway", "lo-fi", 2.56, true));
        masterPlaylist.add(new Song("Voice of the Wind", "DaniSogen", "lo-fi", 2.48, true));
        masterPlaylist.add(new Song("Nature's Temple", "Tenno", "lo-fi", 2.19, true));
        masterPlaylist.add(new Song("Eternity", "Hoogway", "lo-fi", 2.35, true));
        masterPlaylist.add(new Song("Hold You", "mell-o", "lo-fi", 1.44, true));
        masterPlaylist.add(new Song("Nei", "DaniSogen", "lo-fi", 2.37, true));
        masterPlaylist.add(new Song("Perfume", "Lilac", "lo-fi", 2.35, true));
        masterPlaylist.add(new Song("Cascades", "Tribeauthetravler", "lo-fi", 2.12, true));
        masterPlaylist.add(new Song("Devotion", "DaniSogen", "lo-fi", 2.24, true));
        masterPlaylist.add(new Song("Companion", "Krynoze", "lo-fi", 2.33, true));
        masterPlaylist.add(new Song("Without You", "mell-o", "lo-fi", 1.33, true));
        masterPlaylist.add(new Song("Moonshallow", "Yasumu", "lo-fi", 2.40, true));
        masterPlaylist.add(new Song("Planet 9", "No Spirit", "lo-fi", 2.26, true));
        masterPlaylist.add(new Song("Mind Pool", "Dontcry", "lo-fi", 1.34, true));
        masterPlaylist.add(new Song("Escaping Reality", "Yasumu", "lo-fi", 2.17, true));
        masterPlaylist.add(new Song("Sleep Well", "mell-o", "lo-fi", 2.09, true));
        masterPlaylist.add(new Song("Glow", "DLJ", "lo-fi", 2.48, true));
        masterPlaylist.add(new Song("Big Eyes", "Krynoze", "lo-fi", 2.16, true));
        masterPlaylist.add(new Song("Counting", "Yasumu", "lo-fi", 2.57, true));
        masterPlaylist.add(new Song("Ancient Map", "Mondo Loops", "lo-fi", 2.21, true));
        masterPlaylist.add(new Song("Away", "Chiccote's Beats", "lo-fi", 2.40, true));
        masterPlaylist.add(new Song("Miasu", "DaniSongen", "lo-fi", 2.32, true));
        masterPlaylist.add(new Song("a shady place", "", "lo-fi", 2.20, true));
        masterPlaylist.add(new Song("retreat", "Bcalm", "lo-fi", 3.06, true));
        masterPlaylist.add(new Song("Found You", "Hoogway", "lo-fi", 2.36, true));
        masterPlaylist.add(new Song("A Way Home", "H.1", "lo-fi", 309, true));
        masterPlaylist.add(new Song("Safe Haven", "Kulpa", "lo-fi", 2.48, true));
        masterPlaylist.add(new Song("Winds On Mars", "No Spirit", "lo-fi", 2.27, true));
        masterPlaylist.add(new Song("Space 420", "Chau Sara", "lo-fi", 1.45, true));
        masterPlaylist.add(new Song("Flower of Memories", "Tenno", "lo-fi", 2.39, true));
        masterPlaylist.add(new Song("Those Were the Days", "Kulpa", "lo-fi", 3.00, true));
        masterPlaylist.add(new Song("ayla", "Bhxa", "lo-fi", 1.48, true));
        masterPlaylist.add(new Song("As Above So Below", "No Spirit", "lo-fi", 2.17, true));
        masterPlaylist.add(new Song("Get Lost In The Mind's Ocean", "eugenio izzi", "lo-fi", 2.26, true));
        masterPlaylist.add(new Song("Down by the Lake", "TyLuv", "lo-fi", 2.13, true));
        masterPlaylist.add(new Song("Natsukashii", "Raimu", "lo-fi", 3.19, true));
        masterPlaylist.add(new Song("out of blue", "j'san", "lo-fi", 2.36, true));
        masterPlaylist.add(new Song("Bliss", "Kinissue", "lo-fi", 2.57, true));
        masterPlaylist.add(new Song("Blissful", "Krynoze", "lo-fi", 2.45, true));
        masterPlaylist.add(new Song("7 Suns", "No Spirit", "lo-fi", 2.15, true));
        masterPlaylist.add(new Song("The Wild Dance", "Raimu", "lo-fi", 2.35, true));
        masterPlaylist.add(new Song("Afloat", "Yasumu", "lo-fi", 2.30, true));
        masterPlaylist.add(new Song("Stuck in AEther", "Raimu", "lo-fi", 2.35, true));
        masterPlaylist.add(new Song("Capturing the Light", "less.people", "lo-fi", 2.10, true));
        masterPlaylist.add(new Song("Fallen Leaves", "Tibeauthetravler", "lo-fi", 2.18, true));
        masterPlaylist.add(new Song("Equation Of Time", "Hoogway", "lo-fi", 2.45, true));
        masterPlaylist.add(new Song("Counting Rice", "Raimu", "lo-fi", 3.01, true));
        masterPlaylist.add(new Song("In The Zone", "No Spirit", "lo-fi", 2.30, true));
        masterPlaylist.add(new Song("Ekiso", "DaniSogen", "lo-fi", 2.22, true));
        
    }

}